# fly.toml app configuration file generated for delicate-wood-7604 on 2023-06-20T15:15:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-wood-7604"
primary_region = "gig"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
